# Generated by Django 5.0.4 on 2024-04-12 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="users.city",
                verbose_name="Город проведения",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Добавили в избранное",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(to="users.tag", verbose_name="Теги"),
        ),
        migrations.AddField(
            model_name="eventstep",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="events.event",
                verbose_name="Событие",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.eventtype",
                verbose_name="Тип события",
            ),
        ),
        migrations.AddField(
            model_name="eventstep",
            name="speakers",
            field=models.ManyToManyField(
                blank=True, to="events.speaker", verbose_name="Спикеры"
            ),
        ),
    ]
