# Generated by Django 5.0.4 on 2024-04-07 22:39

import django.core.validators
import django.db.models.deletion
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.BooleanField(default=False, verbose_name='Общий флаг активации уведомлений')),
                ('email_notification', models.BooleanField(default=False, verbose_name='Уведомления по электронной почте')),
                ('telegram_notification', models.BooleanField(default=False, verbose_name='Уведомления в телеграм')),
                ('phone_notification', models.BooleanField(default=False, verbose_name='Уведомления по СМС')),
                ('push_notification', models.BooleanField(default=False, verbose_name='Пуш уведомления')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=str, max_length=12, unique=True, validators=[users.validators.validate_mobile], verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(default=str, max_length=150, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_username',
            field=models.CharField(default=str, max_length=150, verbose_name='Ник в телеграм'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_place',
            field=models.CharField(default=str, max_length=150, verbose_name='Место работы(компания)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='yandex_id',
            field=models.PositiveBigIntegerField(blank=True, default=int, verbose_name='Связанный Яндекс ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя содержит недопустимые символы.', regex='^[\\w.@+-]+$'), users.validators.validate_username], verbose_name='Уникальный юзернейм'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='users.notifications', verbose_name='Настройки уведомлений'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tags', to='users.tag', verbose_name='Интересы'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique_user_with_email'),
        ),
    ]
