# Generated by Django 5.0.4 on 2024-04-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notifications_tag_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='yandex_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Связанный Яндекс ID'),
        ),
    ]
