# Generated by Django 5.0.4 on 2024-04-09 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_events', to=settings.AUTH_USER_MODEL, verbose_name='Добавили в избранное'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='users.tag'),
        ),
        migrations.AddField(
            model_name='eventstep',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Событие'),
        ),
        migrations.AddField(
            model_name='eventstep',
            name='speakers',
            field=models.ManyToManyField(blank=True, to='events.speaker', verbose_name='Спикер'),
        ),
    ]
