# Generated by Django 5.0.4 on 2024-04-09 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип события',
                'verbose_name_plural': 'типы событий',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/images/event/preview', verbose_name='Превью-фото события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events/images/event/detail', verbose_name='Фото для страницы события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='users.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='eventstep',
            name='speakers',
            field=models.ManyToManyField(blank=True, to='events.speaker', verbose_name='Спикеры'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.ImageField(blank=True, upload_to='events/images/speakers', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventtype'),
        ),
    ]
