# Generated by Django 5.0.4 on 2024-04-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_favorited_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
