# Generated by Django 5.0.4 on 2024-04-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_delete_tag'),
        ('users', '0002_notifications_tag_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='users.tag'),
        ),
    ]
