# Generated by Django 5.0.4 on 2024-04-11 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_type'),
        ('users', '0002_city_customuser_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.city', verbose_name='Город проведения'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
