# Generated by Django 5.0.4 on 2024-04-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventtype_event_preview_image_alter_event_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventstep',
            options={'default_related_name': 'steps', 'ordering': ('start_time',), 'verbose_name': 'Этап события', 'verbose_name_plural': 'этапы события'},
        ),
    ]
