#!/bin/bash

ENV_FILE=".env"

if [ -z "$ENV_FILE" ]; then
  echo "Переменная ENV_FILE не определена."
  exit 1
fi

if [ -f "$ENV_FILE" ]; then
  echo "Файл $ENV_FILE уже существует. Удаление файла"
  rm "$ENV_FILE"
fi

cat <<EOF > "$ENV_FILE"
DOCKER_USERNAME=$DOCKER_USERNAME
POSTGRES_DB=$POSTGRES_DB
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME
PROJECT_NAME=$PROJECT_NAME
PROJECT_NAME_FRONT=$PROJECT_NAME_FRONT
DOCKER_USERNAME_FRONT=$DOCKER_USERNAME_FRONT
ALLOWED_HOSTS=$ALLOWED_HOSTS
SUPERUSER_PASSWORD=$SUPERUSER_PASSWORD
SECRET_KEY=$SECRET_KEY
DEBUG=$DEBUG
REDIS_HOST=$REDIS_HOST
REDIS_PORT=$REDIS_PORT
EOF

echo "Файл $ENV_FILE успешно создан."
