EVENT_MODES = [
    ("ONLINE", "Онлайн"),
    ("OFFLINE", "Офлайн")
]
EVENT_REGISTRATION_STATUSES = [
    ("OPEN", "Регистрация открыта"),
    ("CLOSED", "Регистрация завершена"),
    ("PENDING", "Ожидание регистрации")
]
MAX_EVENT_ADDRESS = 150
MAX_CITY_NAME = 150
MAX_EVENT_MODE = 7
MAX_EVENT_REG_STATUS = 7
MAX_EVENT_SLUG = 150
MAX_EVENT_TITLE = 150
MAX_FIRST_NAME = 150
MAX_LAST_NAME = 150
MAX_POSITION = 256
MAX_STEP_TITLE = 256
MAX_TAG_TITLE = 150
MAX_WORK_PLACE = 256
