# Generated by Django 5.0.4 on 2024-04-09 09:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(upload_to='ticket/images', verbose_name='QR-код')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный код для кодирования данных о билете в QR-код.', unique=True, verbose_name='Уникальный код')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'билеты',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидание подтверждения'), ('REJECTED', 'Заявка отклонена'), ('CONFIRMED', 'Вы участвуете')], max_length=25, verbose_name='Статус регистрации')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'регистрации',
                'default_related_name': 'ticket_registrations',
            },
        ),
    ]
