# Generated by Django 5.0.4 on 2024-04-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Логин из яндекс, свой логин",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="yandex_id",
            field=models.PositiveBigIntegerField(
                unique=True, verbose_name="Связанный ЯндексID"
            ),
        ),
    ]
